"""DXF builders for centerline, wall solid and QA overlay artifacts."""
from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable

from hscad.adapters.ezdxf_adapter import write_dxf
from hscad.core.models import DrawingEntity


@dataclass
class DxfBuildPlan:
    name: str
    output_path: str
    entities: list[DrawingEntity] = field(default_factory=list)
    notes: list[str] = field(default_factory=list)
    plan_only: bool = False

    def to_record(self) -> dict[str, object]:
        return {
            "name": self.name,
            "output_path": self.output_path,
            "entity_count": len(self.entities),
            "notes": self.notes,
            "plan_only": self.plan_only,
        }


class ResultDxfBuilder:
    def __init__(self, out_dir: str | Path) -> None:
        self.out_dir = Path(out_dir)
        self.out_dir.mkdir(parents=True, exist_ok=True)

    def build_centerline(self, source_entities: Iterable[DrawingEntity]) -> DxfBuildPlan:
        entities = [
            DrawingEntity(
                entity_id=f"CENTER-{ent.entity_id}",
                entity_type="LINE",
                layer="CEN" if ent.layer in {"CEN", "CEN1"} else "RAW_LINES",
                geometry=ent.geometry,
                raw={"source_entity_id": ent.entity_id, "source_layer": ent.layer},
            )
            for ent in source_entities
            if ent.entity_type.upper() in {"LINE", "LWPOLYLINE", "POLYLINE"}
        ]
        path = self.out_dir / "result_centerline.dxf"
        write_dxf(path, entities)
        return DxfBuildPlan("result_centerline", str(path), entities, ["centerline candidate output"])

    def build_wallsolid(self, source_entities: Iterable[DrawingEntity]) -> DxfBuildPlan:
        wall_layers = {"WAL1", "WAL2", "WAL3", "WAL_HATCH"}
        entities = [
            DrawingEntity(
                entity_id=f"WALL-{ent.entity_id}",
                entity_type=ent.entity_type,
                layer=ent.layer if ent.layer in wall_layers else "RAW_LINES",
                geometry=ent.geometry,
                text=ent.text,
                raw={"source_entity_id": ent.entity_id, "source_layer": ent.layer},
            )
            for ent in source_entities
            if ent.layer in wall_layers or ent.entity_type.upper() in {"LWPOLYLINE", "POLYLINE", "LINE"}
        ]
        path = self.out_dir / "result_wallsolid.dxf"
        write_dxf(path, entities)
        return DxfBuildPlan("result_wallsolid", str(path), entities, ["wall/solid candidate output"])

    def build_qa_overlay(self, messages: Iterable[str]) -> DxfBuildPlan:
        entities = []
        for idx, message in enumerate(messages):
            entities.append(
                DrawingEntity(
                    entity_id=f"QA-{idx:04d}",
                    entity_type="TEXT",
                    layer="QA_MARKUP",
                    text=message,
                    geometry={"insert": (0, idx * 500, 0)},
                )
            )
        if not entities:
            entities.append(
                DrawingEntity(
                    entity_id="QA-0000",
                    entity_type="TEXT",
                    layer="QA_MARKUP",
                    text="No QA conflicts generated by next-stage smoke pipeline.",
                    geometry={"insert": (0, 0, 0)},
                )
            )
        path = self.out_dir / "qa_overlay.dxf"
        write_dxf(path, entities)
        return DxfBuildPlan("qa_overlay", str(path), entities, ["QA overlay output"])

    def build_all(self, source_entities: Iterable[DrawingEntity], qa_messages: Iterable[str]) -> list[DxfBuildPlan]:
        entity_list = list(source_entities)
        return [self.build_centerline(entity_list), self.build_wallsolid(entity_list), self.build_qa_overlay(qa_messages)]
