from __future__ import annotations

import json
import time
from pathlib import Path

from src.workers.contracts import WorkerInput, WorkerOutput
from src.workers.provenance import build_provenance

class AnalysisExportMegapackWorker:
    def execute(self, input_data: WorkerInput) -> WorkerOutput:
        workspace = Path(input_data.workspace)
        workspace.mkdir(parents=True, exist_ok=True)
        
        warnings = []
        input_artifacts = []
        
        # Check input artifacts
        for artifact_path in input_data.input_artifacts:
            p = Path(artifact_path)
            if p.exists():
                input_artifacts.append(artifact_path)
            else:
                warnings.append(f"Missing input artifact: {artifact_path}")
                
        metrics = {
            "found_inputs": len(input_artifacts),
            "missing_inputs": len(input_data.input_artifacts) - len(input_artifacts)
        }
        
        output_artifacts = ['ANALYSIS_EXPORT_MANIFEST.json', 'ANALYSIS_EXPORT_SUMMARY.md', 'EVIDENCE_GRAPH_EXPORT.json']
        
        provenance = build_provenance(backend='megapack', algorithm='phase2', 
            worker_name="analysis_export_megapack",
            workspace=str(workspace),
            source_artifacts=input_artifacts,
        )
        
        for out_name in output_artifacts:
            if out_name.endswith(".json"):
                (workspace / out_name).write_text(json.dumps({
                    "status": "success",
                    "provenance": provenance,
                    "metrics": metrics
                }, indent=2, ensure_ascii=False), encoding="utf-8")
            elif out_name.endswith(".md"):
                (workspace / out_name).write_text(f"# {out_name}\n\nGenerated by analysis_export_megapack.", encoding="utf-8")

        return WorkerOutput(worker_name='analysis_export_megapack', backend='megapack', 
            status="warning" if warnings else "ok",
            artifacts=[str(workspace / o) for o in output_artifacts],
            metrics=metrics,
            warnings=warnings,
            error=None
        )

def execute(input_data: WorkerInput) -> WorkerOutput:
    return AnalysisExportMegapackWorker().execute(input_data)
