# Seodaeshin-dong standard drawing layer mappings
architecture_layers:
  wall: [A-WALL, WAL, wall1, wall2, c-wall, 옹벽]
  column: [A-COLUMN, COL, COL XX1, 기둥]
  beam: [A-BEAM, 1-BEAM, 1-B, 보]
  door: [A-DOOR, DOOR, DOOR1, 문]
  window: [A-WINDOW, WID, WIN, WINDOW, 창호]
  ceiling: [A-CEIL, AS-CEIL, 천장]
  insulation: [A-INSUL, INSUL, INSU, 단열재]
  hatch: [A-HATCH, HA, HATC, HATCH, 해치]
  text: [A-TEXT, A-ROOM-TEXT, TEXT, TEXT1, 글씨, 평면]
  dimension: [A-DIM, DIME, DIM, DIM1, 치수]
  grid: [A-GRID, CENTER, CEN, 중심선]
  boundary: [A-BOUNDARY, BOX, FORM, 테두리]
