#!/usr/bin/env bash
set -euo pipefail

mkdir -p docs

{
  echo "# Project Map"
  echo
  echo "Generated by scripts/ai_project_map.sh"
  echo
  echo "## Top-level files and folders"
  echo
  find . -maxdepth 2 \
    -not -path "./.git/*" \
    -not -path "./node_modules/*" \
    -not -path "./.next/*" \
    -not -path "./build/*" \
    -not -path "./dist/*" \
    | sort
} > docs/PROJECT_MAP.md

echo "Updated docs/PROJECT_MAP.md"
